namespace MotoRent.Domain.Entities;

/// <summary>
/// Invoice generated by an agent for their customer.
/// Agents may add their own markup/surcharge and bill customers directly.
/// </summary>
public class AgentInvoice : Entity
{
    public int AgentInvoiceId { get; set; }
    public int AgentId { get; set; }
    public int BookingId { get; set; }

    // Invoice Details

    /// <summary>
    /// Agent's invoice number (e.g., "HTL-INV-001").
    /// </summary>
    public string InvoiceNo { get; set; } = string.Empty;

    /// <summary>
    /// Invoice date.
    /// </summary>
    public DateTimeOffset InvoiceDate { get; set; }

    /// <summary>
    /// Payment due date (optional).
    /// </summary>
    public DateTimeOffset? DueDate { get; set; }

    // Customer (as billed by agent)

    /// <summary>
    /// Customer name on invoice.
    /// </summary>
    public string CustomerName { get; set; } = string.Empty;

    /// <summary>
    /// Customer email for invoice delivery.
    /// </summary>
    public string? CustomerEmail { get; set; }

    /// <summary>
    /// Customer address for invoice.
    /// </summary>
    public string? CustomerAddress { get; set; }

    // Amounts

    /// <summary>
    /// Base rental amount (what shop charges).
    /// </summary>
    public decimal SubTotal { get; set; }

    /// <summary>
    /// Agent's markup/surcharge amount.
    /// </summary>
    public decimal SurchargeAmount { get; set; }

    /// <summary>
    /// Total amount customer pays agent.
    /// </summary>
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// Currency code (default THB).
    /// </summary>
    public string Currency { get; set; } = "THB";

    // Payment Status

    /// <summary>
    /// Payment status: Unpaid, PartiallyPaid, Paid.
    /// </summary>
    public string PaymentStatus { get; set; } = BookingPaymentStatus.Unpaid;

    /// <summary>
    /// Amount paid so far.
    /// </summary>
    public decimal AmountPaid { get; set; }

    // Content

    /// <summary>
    /// Notes to display on invoice.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Payment terms and conditions.
    /// </summary>
    public string? Terms { get; set; }

    /// <summary>
    /// Line items on the invoice.
    /// </summary>
    public List<AgentInvoiceItem> Items { get; set; } = [];

    // Denormalized for Display

    /// <summary>
    /// Agent name for display.
    /// </summary>
    public string? AgentName { get; set; }

    /// <summary>
    /// Booking reference for display.
    /// </summary>
    public string? BookingRef { get; set; }

    // Calculated Properties

    /// <summary>
    /// Outstanding balance.
    /// </summary>
    public decimal BalanceDue => TotalAmount - AmountPaid;

    /// <summary>
    /// Whether invoice is fully paid.
    /// </summary>
    public bool IsPaid => PaymentStatus == BookingPaymentStatus.FullyPaid;

    public override int GetId() => AgentInvoiceId;
    public override void SetId(int value) => AgentInvoiceId = value;
}

/// <summary>
/// Line item on an agent invoice.
/// </summary>
public class AgentInvoiceItem
{
    /// <summary>
    /// Item description (e.g., "Honda Click 125cc - 5 days").
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Quantity (e.g., number of days or vehicles).
    /// </summary>
    public int Quantity { get; set; } = 1;

    /// <summary>
    /// Unit price.
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Line total (Quantity × UnitPrice).
    /// </summary>
    public decimal Amount { get; set; }
}
