using System.Text.Json.Serialization;

namespace MotoRent.Domain.Entities;

/// <summary>
/// Represents the financial asset record for a vehicle.
/// Tracks acquisition, depreciation settings, and current book value.
/// </summary>
public class Asset : Entity
{
    public int AssetId { get; set; }

    #region Vehicle Reference

    /// <summary>
    /// The vehicle this asset record tracks.
    /// </summary>
    public int VehicleId { get; set; }

    /// <summary>
    /// Denormalized vehicle name for display.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? VehicleName { get; set; }

    /// <summary>
    /// Denormalized license plate for display.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? LicensePlate { get; set; }

    #endregion

    #region Acquisition Details

    /// <summary>
    /// Date the asset was acquired/purchased.
    /// </summary>
    public DateTimeOffset AcquisitionDate { get; set; }

    /// <summary>
    /// Original purchase price of the asset.
    /// </summary>
    public decimal AcquisitionCost { get; set; }

    /// <summary>
    /// Date the asset was first rented (triggers "Day Out of Door" depreciation).
    /// Null if never rented.
    /// </summary>
    public DateTimeOffset? FirstRentalDate { get; set; }

    /// <summary>
    /// Purchase invoice or reference number.
    /// </summary>
    public string? AcquisitionRef { get; set; }

    /// <summary>
    /// Vendor/dealer from whom asset was purchased.
    /// </summary>
    public string? VendorName { get; set; }

    /// <summary>
    /// Whether this asset existed before system implementation.
    /// Affects initial book value calculation.
    /// </summary>
    public bool IsPreExisting { get; set; }

    /// <summary>
    /// For pre-existing assets: the book value at system implementation.
    /// </summary>
    public decimal? InitialBookValue { get; set; }

    /// <summary>
    /// Date this asset was entered into the system (for pre-existing assets).
    /// </summary>
    public DateTimeOffset? SystemEntryDate { get; set; }

    #endregion

    #region Depreciation Settings

    /// <summary>
    /// Depreciation method used for this asset.
    /// </summary>
    public DepreciationMethod DepreciationMethod { get; set; } = DepreciationMethod.StraightLine;

    /// <summary>
    /// Useful life in months.
    /// </summary>
    public int UsefulLifeMonths { get; set; } = 60; // Default 5 years

    /// <summary>
    /// Residual (salvage) value at end of useful life.
    /// </summary>
    public decimal ResidualValue { get; set; }

    /// <summary>
    /// For Day Out of Door: percentage to depreciate on first rental.
    /// Example: 0.20 for 20%.
    /// </summary>
    public decimal? DayOutOfDoorPercent { get; set; }

    /// <summary>
    /// For Declining Balance: annual depreciation rate.
    /// Example: 0.25 for 25% per year.
    /// </summary>
    public decimal? DecliningBalanceRate { get; set; }

    /// <summary>
    /// For Custom method: serialized monthly schedule.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<CustomDepreciationEntry>? CustomSchedule { get; set; }

    #endregion

    #region Current Values (Calculated)

    /// <summary>
    /// Current book value (acquisition cost minus accumulated depreciation).
    /// Updated when depreciation is recorded.
    /// </summary>
    public decimal CurrentBookValue { get; set; }

    /// <summary>
    /// Total accumulated depreciation to date.
    /// </summary>
    public decimal AccumulatedDepreciation { get; set; }

    /// <summary>
    /// Total expenses recorded against this asset.
    /// </summary>
    public decimal TotalExpenses { get; set; }

    /// <summary>
    /// Total revenue generated by this asset from rentals.
    /// </summary>
    public decimal TotalRevenue { get; set; }

    /// <summary>
    /// Last date depreciation was calculated/recorded.
    /// </summary>
    public DateTimeOffset? LastDepreciationDate { get; set; }

    #endregion

    #region Status

    /// <summary>
    /// Asset status: Active, Disposed, WriteOff.
    /// </summary>
    public AssetStatus Status { get; set; } = AssetStatus.Active;

    /// <summary>
    /// If disposed: disposal date.
    /// </summary>
    public DateTimeOffset? DisposalDate { get; set; }

    /// <summary>
    /// If disposed: amount received from sale.
    /// </summary>
    public decimal? DisposalAmount { get; set; }

    /// <summary>
    /// Gain or loss on disposal (DisposalAmount - CurrentBookValue at disposal).
    /// </summary>
    public decimal? DisposalGainLoss { get; set; }

    /// <summary>
    /// Notes about this asset.
    /// </summary>
    public string? Notes { get; set; }

    #endregion

    #region Loan Reference

    /// <summary>
    /// If this asset was financed, the loan ID.
    /// </summary>
    public int? AssetLoanId { get; set; }

    #endregion

    public override int GetId() => this.AssetId;
    public override void SetId(int value) => this.AssetId = value;

    #region Calculated Properties

    /// <summary>
    /// Depreciable base (Acquisition Cost - Residual Value).
    /// </summary>
    [JsonIgnore]
    public decimal DepreciableBase => this.AcquisitionCost - this.ResidualValue;

    /// <summary>
    /// Monthly depreciation for straight-line method.
    /// </summary>
    [JsonIgnore]
    public decimal MonthlyDepreciationStraightLine => this.UsefulLifeMonths > 0
        ? this.DepreciableBase / this.UsefulLifeMonths
        : 0;

    /// <summary>
    /// Remaining useful life in months.
    /// </summary>
    [JsonIgnore]
    public int RemainingUsefulLifeMonths
    {
        get
        {
            var startDate = this.IsPreExisting && this.SystemEntryDate.HasValue
                ? this.SystemEntryDate.Value
                : this.AcquisitionDate;
            var monthsElapsed = (int)((DateTimeOffset.Now - startDate).TotalDays / 30.44);
            return Math.Max(0, this.UsefulLifeMonths - monthsElapsed);
        }
    }

    /// <summary>
    /// Net profit/loss to date (Revenue - Expenses - Depreciation).
    /// </summary>
    [JsonIgnore]
    public decimal NetProfitLoss => this.TotalRevenue - this.TotalExpenses - this.AccumulatedDepreciation;

    /// <summary>
    /// ROI percentage ((Revenue - Expenses - Depreciation) / Acquisition Cost * 100).
    /// </summary>
    [JsonIgnore]
    public decimal ROIPercent => this.AcquisitionCost > 0
        ? (this.NetProfitLoss / this.AcquisitionCost) * 100
        : 0;

    #endregion
}

/// <summary>
/// Entry for custom depreciation schedule.
/// </summary>
public class CustomDepreciationEntry
{
    public int MonthNumber { get; set; }
    public decimal Amount { get; set; }
}
