-- AgentInvoice table
-- Stores invoices generated by agents for their customers
CREATE TABLE "AgentInvoice"
(
    "AgentInvoiceId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "AgentId" INT GENERATED ALWAYS AS (("Json"->>'AgentId')::INT) STORED,
    "BookingId" INT GENERATED ALWAYS AS (("Json"->>'BookingId')::INT) STORED,
    "InvoiceNo" VARCHAR(50) GENERATED ALWAYS AS (("Json"->>'InvoiceNo')::VARCHAR(50)) STORED,
    "InvoiceDate" TIMESTAMPTZ NULL,
    "SubTotal" NUMERIC(18,2) GENERATED ALWAYS AS (("Json"->>'SubTotal')::NUMERIC(18,2)) STORED,
    "SurchargeAmount" NUMERIC(18,2) GENERATED ALWAYS AS (("Json"->>'SurchargeAmount')::NUMERIC(18,2)) STORED,
    "TotalAmount" NUMERIC(18,2) GENERATED ALWAYS AS (("Json"->>'TotalAmount')::NUMERIC(18,2)) STORED,
    "AmountPaid" NUMERIC(18,2) GENERATED ALWAYS AS (("Json"->>'AmountPaid')::NUMERIC(18,2)) STORED,
    "PaymentStatus" VARCHAR(20) GENERATED ALWAYS AS (("Json"->>'PaymentStatus')::VARCHAR(20)) STORED,
    "CustomerName" VARCHAR(100) GENERATED ALWAYS AS (("Json"->>'CustomerName')::VARCHAR(100)) STORED,
    "AgentName" VARCHAR(200) GENERATED ALWAYS AS (("Json"->>'AgentName')::VARCHAR(200)) STORED,
    "BookingRef" VARCHAR(10) GENERATED ALWAYS AS (("Json"->>'BookingRef')::VARCHAR(10)) STORED,
    "Json" JSONB NOT NULL,
    "tenant_id" VARCHAR(50) NOT NULL DEFAULT current_setting('app.current_tenant'),
    "CreatedBy" VARCHAR(50) NOT NULL DEFAULT 'system',
    "ChangedBy" VARCHAR(50) NOT NULL DEFAULT 'system',
    "CreatedTimestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "ChangedTimestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "AgentInvoice" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_agentinvoice ON "AgentInvoice" USING ("tenant_id" = current_setting('app.current_tenant'));

CREATE INDEX IX_AgentInvoice_AgentId ON "AgentInvoice"("AgentId");
CREATE INDEX IX_AgentInvoice_BookingId ON "AgentInvoice"("BookingId");
CREATE UNIQUE INDEX IX_AgentInvoice_InvoiceNo ON "AgentInvoice"("tenant_id", "InvoiceNo") WHERE "InvoiceNo" IS NOT NULL;
CREATE INDEX IX_AgentInvoice_PaymentStatus ON "AgentInvoice"("PaymentStatus");
CREATE INDEX IX_AgentInvoice_InvoiceDate ON "AgentInvoice"("InvoiceDate");
CREATE INDEX IX_AgentInvoice_TenantId ON "AgentInvoice"("tenant_id");
