-- AgentInvoice table
-- Stores invoices generated by agents for their customers
CREATE TABLE [<schema>].[AgentInvoice]
(
    [AgentInvoiceId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    -- Foreign Keys
    [AgentId] AS CAST(JSON_VALUE([Json], '$.AgentId') AS INT),
    [BookingId] AS CAST(JSON_VALUE([Json], '$.BookingId') AS INT),
    -- Invoice Details
    [InvoiceNo] AS CAST(JSON_VALUE([Json], '$.InvoiceNo') AS NVARCHAR(50)),
    -- DATETIMEOFFSET column (regular column, not computed - per CLAUDE.md rules)
    [InvoiceDate] DATETIMEOFFSET NULL,
    -- Amounts
    [SubTotal] AS CAST(JSON_VALUE([Json], '$.SubTotal') AS DECIMAL(18,2)),
    [SurchargeAmount] AS CAST(JSON_VALUE([Json], '$.SurchargeAmount') AS DECIMAL(18,2)),
    [TotalAmount] AS CAST(JSON_VALUE([Json], '$.TotalAmount') AS DECIMAL(18,2)),
    [AmountPaid] AS CAST(JSON_VALUE([Json], '$.AmountPaid') AS DECIMAL(18,2)),
    -- Status
    [PaymentStatus] AS CAST(JSON_VALUE([Json], '$.PaymentStatus') AS NVARCHAR(20)),
    -- Customer
    [CustomerName] AS CAST(JSON_VALUE([Json], '$.CustomerName') AS NVARCHAR(100)),
    -- Denormalized
    [AgentName] AS CAST(JSON_VALUE([Json], '$.AgentName') AS NVARCHAR(200)),
    [BookingRef] AS CAST(JSON_VALUE([Json], '$.BookingRef') AS NVARCHAR(10)),
    -- JSON storage
    [Json] NVARCHAR(MAX) NOT NULL,
    -- Audit columns
    [CreatedBy] VARCHAR(50) NOT NULL DEFAULT 'system',
    [ChangedBy] VARCHAR(50) NOT NULL DEFAULT 'system',
    [CreatedTimestamp] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    [ChangedTimestamp] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
)

-- Index for querying by agent
CREATE INDEX IX_AgentInvoice_AgentId ON [<schema>].[AgentInvoice]([AgentId])

-- Index for querying by booking
CREATE INDEX IX_AgentInvoice_BookingId ON [<schema>].[AgentInvoice]([BookingId])

-- Unique index on InvoiceNo (agent invoice numbers should be unique)
CREATE UNIQUE INDEX IX_AgentInvoice_InvoiceNo ON [<schema>].[AgentInvoice]([InvoiceNo]) WHERE [InvoiceNo] IS NOT NULL

-- Index for querying by payment status
CREATE INDEX IX_AgentInvoice_PaymentStatus ON [<schema>].[AgentInvoice]([PaymentStatus])

-- Index for querying by invoice date
CREATE INDEX IX_AgentInvoice_InvoiceDate ON [<schema>].[AgentInvoice]([InvoiceDate])
